apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: trailerpark
spec:
  image: "ghcr.io/bharatrajani/trailerpark:v0.4.0"
  executor: containerd-shim-spin
  replicas: 2
  runtimeConfig:
    loadFromSecret: trailerpark-runtime-config
  variables:
    - name: allowed_channel
      valueFrom:
        secretKeyRef:
          name: trailerpark
          key: allowed_channel
          optional: false
    - name: trigger_on_emoji_code
      valueFrom:
        secretKeyRef:
          name: trailerpark
          key: trigger_on_emoji_code
          optional: false
    - name: slack_token
      valueFrom:
        secretKeyRef:
          name: trailerpark
          key: slack_token
          optional: false
    - name: slack_signing_secret
      valueFrom:
        secretKeyRef:
          name: trailerpark
          key: slack_signing_secret
          optional: false
    - name: runs_on
      valueFrom:
        secretKeyRef:
          name: trailerpark
          key: runs_on
          optional: false
---
apiVersion: v1
kind: Secret
metadata:
  name: trailerpark-runtime-config
type: Opaque
data:
  runtime-config.toml: W2tleV92YWx1ZV9zdG9yZS5kZWZhdWx0XQp0eXBlID0gInJlZGlzIgp1cmwgPSAicmVkaXM6Ly9yZWRpcy1zZXJ2aWNlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OSI=
